spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/DBFD22
    username: postgres
    password: 12345
  flyway:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: https://sts.windows.net/09d8c2b8-850c-4d96-a486-cbc8dfe86610/


zoho:
  clientId: 1000.L6K1UKD41XF9N28QKFX3O8UA0KGWFN
  clientSecret: 144429c45051a2c433bc1ae10f959db5372f373db9
  refreshToken: 1000.4c3f3fe6fba9923d56d19e93cb8ebc6e.0837b64e6ec867b701308ffaf8876e1c

  caching:
    zohoOauthTokenTTL: 3400000

azure:
  active-directory:
    client-id: a9437014-a167-43fb-8be0-c00bc7ff2a29
    client-secret: _tJ8Q~x.fIfaoUwwx.zS5h4QbMd.MFqvOSOtqaOK
    tenant-id: 09d8c2b8-850c-4d96-a486-cbc8dfe86610
    app-id-uri: api://a9437014-a167-43fb-8be0-c00bc7ff2a29


