spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/frontdesk_be
    username: postgres
    password: bhuni1106
  flyway:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
